services:
  quest-to-solvin:
    image: fernandogonzzz/quest-to-solvin:latest
    env_file:
      - .env
    ports:
      - "8501:8501"
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
